### ISSUE TITLE
Replace USAJOBS/Login.gov with basic authentication

### ISSUE THREAD

**Issue by amprokop** [chhsinnovation/openopps-platform#1]
### Who
California state users who don't have federal govt logins.

### What
Replace the federal login flow with the simplest possible username/password login. 

We'll need to:
- Modify the UI to have a sign in page
- Create DB tables to store username and salted hashed password
- Send emails to confirm email address
- Handle sessions
- Replace the authentication logic handling pages

### Why
- Users need to be able to sign up and log in to open opportunities

### Acceptance Criteria
- User can sign up and choose username and password
- Username must be CA email address 
- User receives an email and can confirm email address by clicking a link in the email
- User can log in with username and password
- Without being logged in, users cannot create or apply for opportunities

**Comment by bmcorum** [comment]
@amprokop I tested a few weeks back. As long as you do not have a LOGINGOV environment variable defined or at least have it set to false, the application will revert to local authentication. There is a self registration form as well as a basic username/password login page. The registration form asks for name, email, agency, location. Once you register you must confirm your email address by clicking a one-time use link emailed to you. During the verification the user will then be prompted to set their password for the first time. Using local authentication will also give you access to the password reset/forgotten functionality.

**Comment by amprokop** [comment]
Awesome, so great that this is all still in place. I'll get MailCatcher up and running and add some screenshots and close this out. Thanks, @bmcorum!

**Comment by amprokop** [comment]
No screenshots, but we had multiple people test this.

**Comment by amprokop** [comment]
Closing.
