### ISSUE TITLE
Can't apply for opportunity because location is not selected

### ISSUE THREAD

**Issue by amprokop** [chhsinnovation/openopps-platform#16]
See the GIF. @DavidEBest, would you mind trying to reproduce this one just in case there's something funky going on with my local location data that's causing this? 

![location error](https://user-images.githubusercontent.com/3781835/81731432-e8b06d80-945c-11ea-8505-2675abb9f8f5.gif)

**Comment by DavidEBest** [comment]
That's super weird. If you click on 'Search for this location', what do you get? I get a reasonable list of search results.

<img width="627" alt="Screen Shot 2020-05-14 at 4 40 38 PM" src="https://user-images.githubusercontent.com/933586/81983944-226ea900-9602-11ea-9523-5f671d63f477.png">

**Comment by DavidEBest** [comment]
I get the same behavior. Looking in the database, it looks like that profile location is saved in a different spot. The current system saves the searched 'City, State' field as a `tagentity` record, but the application process is checking for the `midas_user.city_name` field. I bet that login.gov was populating that value.

Here's the relevant check: https://github.com/openopps/openopps-platform/blob/666f86c76f4a1051abd0cb3750ee700dead58af2/assets/js/backbone/apps/tasks/show/views/task_item_view.js#L497

**Comment by bmcorum** [comment]
@amprokop and @DavidEBest this is side affect (for lack of a better term) of us using USAJOBS and Login.gov. We were loading location information from USAJOBS. If you look there is a cityName, countrySubdivisionId, and countryID on the midas_user table. The 2 id columns map to the country subdivision table (list of state, territories and provinces) and the country table. You could either convert back to pulling location from the tagentity table or may just need to update the location on profile edit to update the cityName,  countrySubdivisionId, and countryID. The field itself is probably mapping to a entry from the tagentity table but the profile view as well as you current session user object is expecting a cityName, countrySubdivision object and country object. So you may have to adjust a few other views around the application if you decide to go the route of re-instituting use of the tagentity for locations.

**Comment by DavidEBest** [comment]
@bmcorum Thanks for the background. It probably makes the most sense to revert back to the tagentity based locations.
