### ISSUE TITLE
Replace mentions of the federal government with California state

### ISSUE THREAD

**Issue by amprokop** [chhsinnovation/openopps-platform#2]
### What
Remove mentions of the US Federal government

### Why
So users can know they are searching for tasks in California state

### Acceptance Criteria
- All mentions of the federal government are changed to California state
- Bonus points: All mentions are templatized and the location is controlled by a variable set in one place instead of scattered throughout the copy

**Comment by DavidEBest** [comment]
I'll take this on. I'll start by pulling in the changes from here: https://github.com/chhsdata/openopps-platform/commit/9b747d7ce0a4caa6e5d168ff0d262eb61462d170
