### ISSUE TITLE
Double check imagemagick install on AWS

### ISSUE THREAD

**Issue by DavidEBest** [chhsinnovation/openopps-platform#27]
For bug tracker item #6, can you confirm that `imagemagick` is installed on the AWS machine?

The upload works for me after I locally installed both `imagemagick` and `graphicsmagick`. I see that `graphicsmagick` is already listed in the `Dockerfile`.

https://docs.google.com/document/d/1hAcBhmFvtNG8KtQU7aVgDEIVpXbEWoXYyevpUGS1324/edit

**Comment by xjensen** [comment]
Hi @DavidEBest, thanks for looking into this! Couple things to note.

While the [dockerfile in the staging branch](https://github.com/chhsinnovation/openopps-platform/blob/staging/Dockerfile) does contain Imagemagick, there are other significant differences in that dockerfile that could still be throwing things off. At the top of the list, I switched the OS from Ubuntu to Alpine. Some other OS-level dependencies could be missing.

I'll take a look, more to come.
