### ISSUE TITLE
Change header and footer to add California branding

### ISSUE THREAD

**Issue by amprokop** [chhsinnovation/openopps-platform#3]
### What
Change header and footer so Open Opps has branding showing California

### Acceptance Criteria
- Open Opps has California branding on the header and footer of the main page

### Related Tickets 
See https://github.com/chhsdata/openopps-platform/commit/a1e6915c54eccb606e65a601b427036a6e1c4e5d from the old fork.

**Comment by DavidEBest** [comment]
I'll take this on to refamiliarize myself with some of the code.
